#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'Test data file not found. Run "mqttest /path/to/testfile/"'
    echo 'Test data file example:'
    echo '```'
    echo 'pub;my-mqtt-host.local.reksoft.ru;1883;anytopic;testtest;wrongpass;0'
    echo 'sub;my-mqtt-host.local;1883;anytopic;testtest;testtest;1'
    echo '```'
    exit 1
fi

export testdata=$1
echo "Using test-data $testdata:"
cat $testdata

echo ""
echo "Starting test execution..."
echo ""

file=$(cat "$testdata")

for line in ${file[@]}
do
    action=$(echo $line | cut -d ";" -f 1)
    host=$(echo $line | cut -d ";" -f 2)
    port=$(echo $line | cut -d ";" -f 3)
    topic=$(echo $line | cut -d ";" -f 4)
    user=$(echo $line | cut -d ";" -f 5)
    password=$(echo $line | cut -d ";" -f 6)
    expected=$(echo $line | cut -d ";" -f 7)
    command="mqttx $action -h $host -p $port -t $topic -u $user -P $password "
    echo $command
    echo "Expected result: $expected"
    $command > /tmp/mqttx.log
    cat /tmp/mqttx.log | grep "Error" >> /dev/null
    result=$?
    echo "Result: $result"
    if [ "$expected" != "$result" ]; then
        cat /tmp/mqttx.log
        exit 1
    fi
    echo ""
done
